### ISSUE TITLE
UnboundlocalError: Local Variable 'images'

### ISSUE THREAD

**Issue by JamiDEV** [EGirlEnthusiast/Coomer.party-scraper#3]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mymac/Desktop/Coomer.party-scraper-main/coomer.party_scraper.py", line 131, in <module>
    ScanningPosts(url)
  File "/Users/mymac/Desktop/Coomer.party-scraper-main/coomer.party_scraper.py", line 109, in ScanningPosts
    coom()
  File "/Users/mymac/Desktop/Coomer.party-scraper-main/coomer.party_scraper.py", line 50, in coom
    for image in images:
UnboundLocalError: local variable 'images' referenced before assignment

It appears this is only a problem scraping videos.

**Comment by gosadaque** [comment]
Same error here. Scraping videos is set to false.

```
No images found in this entry

Traceback (most recent call last):
  File "scraper.py", line 123, in <module>
    coom()
  File "scraper.py", line 50, in coom
    for image in images:
UnboundLocalError: local variable 'images' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scraper.py", line 131, in <module>
    ScanningPosts(url)
  File "scraper.py", line 109, in ScanningPosts
    coom()
  File "scraper.py", line 50, in coom
    for image in images:
UnboundLocalError: local variable 'images' referenced before assignment

```

**Comment by EGirlEnthusiast** [comment]
Ive been busy so sorry this took so long, seems to be an issue created when the first post attempting to scrape has no image attached, ive created a fix, give it a test.
